---
galaxy_info:
  role_name: kibana
  description: "Kibana 7.17 в Docker"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies:
  - role: docker
