---
galaxy_info:
  role_name: prometheus
  description: "Prometheus server (apt) с конфигом для web-серверов"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies: []
