---
- name: reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: restart nginx-log-exporter
  ansible.builtin.systemd:
    name: prometheus-nginxlog-exporter
    state: restarted

- name: restart filebeat
  community.docker.docker_container:
    name: filebeat
    state: started
    restart: true
