---
galaxy_info:
  role_name: elasticsearch
  description: "Elasticsearch 7.17 single-node в Docker"
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
dependencies:
  - role: docker
